export const UPDATE_BURGER_CONSTRUCTOR_BUN = 'UPDATE_BURGER_CONSTRUCTOR_BUN';
export const ADD_BURGER_CONSTRUCTOR_INGREDIENTS = 'ADD_BURGER_CONSTRUCTOR_INGREDIENTS';
export const DELETE_BURGER_CONSTRUCTOR_INGREDIENTS = 'DELETE_BURGER_CONSTRUCTOR_INGREDIENTS';
export const SET_BURGER_CONSTRUCTOR_INGREDIENTS = 'SET_BURGER_CONSTRUCTOR_INGREDIENTS';
export const SET_BURGER_CONSTRUCTOR_INITIAL_STATE = 'SET_BURGER_CONSTRUCTOR_INITIAL_STATE';

export function getBurgerConstructorState(state) {
    return state.burgerConstructor
}